cloud:
  aws:
    credentials:
      access-key: AKIAYENEEJND6CZYHT26
      secret-key: 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
    region:
      static: ap-southeast-2
    stack:
      auto: false

application:
  bucket:
    name: childrencare


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090